### ISSUE TITLE
Branch questions don't work

### ISSUE THREAD

**Issue by trefilovandrei** [iteratehq/iterate-ios#104]
**Describe the bug**
Branch questions don't work. Maybe it can be fixed on the web side

**To Reproduce**
1. Create a survey with a Start rating
2. Add the branches
3. Go to the app and try to see branch questions

**Expected behavior**
When I choose star value I want to see another question

**Screenshots**
What expected:

https://github.com/iteratehq/iterate-ios/assets/166369953/dd709aa5-9e19-429c-9a5e-4e23bc4efcd4

What we see:

https://github.com/iteratehq/iterate-ios/assets/166369953/bf591991-a23f-4420-8049-e104fee35aed

**Device (please complete the following information):**
 - Simulator: 15 pro max
 - OS: 17.4

**Comment by msingleton** [comment]
@trefilovandrei could you email me a link to your survey in Iterate? mike@iteratehq.com

**Comment by trefilovandrei** [comment]
> @trefilovandrei could you email me a link to your survey in Iterate? [mike@iteratehq.com](mailto:mike@iteratehq.com)

Sent. Thanks for the fast reaction 🙏

**Comment by trefilovandrei** [comment]
The solution: use only String properties.
@msingleton thanks for your help! 🙏
