### ISSUE TITLE
Swift Package Manager (SPM) support

### ISSUE THREAD

**Issue by markedwardmurray** [iteratehq/iterate-ios#66]
Please add Swift Package Manager support. In our projects we're moving away from Cocoapods towards SPM and would like to be able to use it for all of our dependencies in the future.

You'll likely also need to change your tagging convention to remove the `v` prefix, since SPM is opinionated to using semantic versioning with numbers only.

**Comment by clausjoergensen** [comment]
Almost a year later, and still no SPM support? It takes minutes to setup, c'mon developers get a move on.

We have to maintain our own fork with SPM support in order to use this SDK since we have zero intentions of ever using CocoaPods again.

**Comment by msingleton** [comment]
@clausjoergensen @markedwardmurray apologies for the terrible delay but this is fixed
