### ISSUE TITLE
Main Thread Checker warning in v1.0.9

### ISSUE THREAD

**Issue by jvknapp** [iteratehq/iterate-ios#75]
**Bug Description**
I just took the Iterate SDK v1.0.9 update (with custom font support), and I noticed a new warning from the Main Thread Checker when triggering a survey in-app.  This doesn't seem like a big issue as it's just a warning, but I figured I would flag it for you since this was just introduced in this recent release.

**To Reproduce**
1. Update to Iterate SDK v1.0.9
2. Preview any survey and trigger it
3. Note the `CFNetwork` warning from the Main Thread Checker on line 106 of `SurveyViewController.swift`:

> Synchronous URL loading of [survey_url] should not occur on this application's main thread as it may lead to UI unresponsiveness. Please switch to an asynchronous networking API such as URLSession.

**Expected behavior**
There should be no warnings from the Main Thread Checker.

**Device:**
 - Device: iPhone 12 Pro
 - Xcode Version: 14.0
 - OS: iOS 16.0

**Comment by lankybutmacho** [comment]
Thank you for the report, fixed in [v1.0.10](https://github.com/iteratehq/iterate-ios/releases/tag/v1.0.10)
