### ISSUE TITLE
Not receiving any indicating user survey completion.

### ISSUE THREAD

**Issue by JaydipGadhiya** [iteratehq/iterate-ios#93]
**Describe the bug**
After making the survey preview available to the user, there's a lack of callbacks received upon the completion or dismissal of the survey.

**To Reproduce**
1. dismiss or complement any survey

**Expected behavior**
Should receive any callback using protocol which indicate about survey ongoing status

**Device (please complete the following information):**
 - Device: iPhone13
 - OS: 17.0.1

**Additional context**

**Comment by msingleton** [comment]
@JaydipGadhiya we followed up with you over email, but just confirming here we don't yet support callbacks on iOS but plan to add them in the future so you'll be able to get this data
